apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: TransformationPolicy
metadata:
  name: big-payloads
  namespace: ops-team
spec:
  applyToRoutes:
  - route:
      labels:
        big-payload: "true"
  config:
    request:
      injaTemplate:
        headers:
          x-my-custom-header:
            text: 'my-custom-value'