apiVersion: v1
kind: Namespace
metadata:
  name: app-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-1
  namespace: app-1
---
apiVersion: v1
kind: Service
metadata:
  name: app-1
  namespace: app-1
spec:
  selector:
    app: app-1
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8081
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  namespace: app-1
  labels:
    app: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
      version: v1
  template:
    metadata:
      labels:
        app: app-1
        version: v1
    spec:
      serviceAccountName: app-1    
      containers:
      - name: app-1
        image: nicholasjackson/fake-service:v0.7.8
        ports:
        - containerPort: 8081
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8081"
        - name: "NAME"
          value: "app-1"
        - name: "MESSAGE"
          value: "Hello From App-1"
---
apiVersion: v1
kind: Service
metadata:
  name: app-1-default
  namespace: app-1
spec:
  selector:
    app: app-1-default
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8081
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-default
  namespace: app-1
  labels:
    app: app-1-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1-default
      version: v1
  template:
    metadata:
      labels:
        app: app-1-default
        version: v1
    spec:
      serviceAccountName: app-1    
      containers:
      - name: app-1-default
        image: nicholasjackson/fake-service:v0.7.8
        ports:
        - containerPort: 8081
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8081"
        - name: "NAME"
          value: "app-1-default"
        - name: "MESSAGE"
          value: "Hello From App-1 Default"
