apiVersion: k3d.io/v1alpha3
kind: Simple
name: gloo
image: rancher/k3s:v1.30.8-k3s1
network: k3d-cluster-network
ports:
  - port: 8090:8090
    nodeFilters:
      - loadbalancer
  - port: 8200:8200
    nodeFilters:
      - loadbalancer
  - port: 4317:4317
    nodeFilters:
      - loadbalancer 
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true