apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: httpbin
  namespace: ops-team
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: north-south-gw
      namespace: ops-team
      cluster: gloo
  workloadSelectors: []
  http:
    - name: httpbin
      forwardTo:
        destinations:
          - kind: EXTERNAL_SERVICE
            ref:
              name: httpbin
              namespace: ops-team
              cluster: gloo
            port:
              number: 443
            weight: 50
          - ref:
              name: httpbin
              namespace: httpbin
              cluster: gloo
            port:
              number: 8000
            weight: 50