apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: extauth
  namespace: gloo-system
  labels:
    app: gloo
    gloo: extauth
spec:
  useHttp2: true
  pipe:
    path: "/var/lib/gloo/.sock"
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: rate-limit
  namespace: gloo-system
  labels:
    app: gloo
    gloo: rate-limit
spec:
  healthChecks:
  - timeout: 5s
    interval: 10s
    noTrafficInterval: 10s
    unhealthyThreshold: 3
    healthyThreshold: 3
    grpcHealthCheck:
      serviceName: ratelimit
  static:
    hosts:
      - addr: 127.0.0.1
        port: 18081
    serviceSpec:
      grpc: {}