apiVersion: admin.gloo.solo.io/v2
kind: ExtAuthServer
metadata:
  name: default-server
  namespace: ops-team
spec:
  destinationServer:
    port:
      number: 8083
    ref:
      cluster: gloo
      name: ext-auth-service
      namespace: gloo-mesh-addons
