apiVersion: security.policy.gloo.solo.io/v2
kind: WAFPolicy
metadata:
  name: spring4jshell
  namespace: ops-team
spec:
  applyToRoutes:
  - route:
      labels:
        waf: "true"
  config:
    disableCoreRuleSet: true
    customInterventionMessage: 'SpringShell malicious payload'
    customRuleSets:
      - ruleStr: |
          SecRuleEngine On
          SecRule REQUEST_HEADERS_NAMES
            "@contains spring.cloud.function.routing-expression"
            "id:1001,deny,status:403,log,t:lowercase,msg:'Potential Remote Command Execution: Spring4Shell CVE-2022-22963'"
      - ruleStr: |
          SecRuleEngine On
          SecRequestBodyAccess On
          SecRule REQUEST_BODY
            "@contains class.module.classLoader.resources.context.parent.pipeline.first.pattern"
            "id:1002,phase:2,deny,status:403,log,msg:'Potential Remote Command Execution: Spring4Shell CVE-2022-22965'"