apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: route-option-httpbin
  namespace: httpbin
spec:
  options:
    stagedTransformations:
      early:
        requestTransforms:
          - matcher:
              prefix: /
            requestTransformation:
              transformationTemplate:
                passthrough: {}   #  <<====== NOTE the addition of the passthrough directive
                headers:
                  x-my-custom-header:
                    text: 'my-custom-value'
